name: Test Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25

      - name: Build package
        run: nix build

      - name: Verify package structure
        run: |
          # Check if the compatibility tool files exist
          test -f result/share/steam/compatibilitytools.d/proton-cachyos/compatibilitytool.vdf
          test -f result/share/steam/compatibilitytools.d/proton-cachyos/proton

          # Check if proton is executable
          test -x result/share/steam/compatibilitytools.d/proton-cachyos/proton

      - name: Check Nix flake
        run: nix flake check
