name: Update Package Version

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for Updates
        id: check
        run: |
          # Get latest version from mirror
          LATEST=$(curl -s 'https://mirror.cachyos.org/repo/x86_64_v3/cachyos-v3/' | grep -Po 'proton-cachyos-1:\d+\.\d+\.\d+-\d+-x86_64_v3\.pkg\.tar\.zst' | sort -V | tail -n1)
          BASE=$(echo $LATEST | grep -Po '(?<=:)\d+\.\d+(?=\.)')
          RELEASE=$(echo $LATEST | grep -Po '\d+(?=-\d+-x86_64)')

          # Get the hash
          URL="https://mirror.cachyos.org/repo/x86_64_v3/cachyos-v3/$LATEST"
          HASH=$(nix-prefetch-url $URL)

          # Update versions.json
          cat > versions.json <<EOF
          {
            "base": "$BASE",
            "release": "$RELEASE",
            "hash": "sha256-$(echo $HASH | base64)"
          }
          EOF

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'proton-cachyos: update to latest version'
          title: 'Update proton-cachyos'
          branch: update-proton-cachyos
          delete-branch: true
